=== aphawkins/old/Useful/Config/Useful.Config.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Andrew Hawkins (Home) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="UsefulConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SchemaPath" type="xs:string" />
        <xs:element name="Consumers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Consumer" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="DataService">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="File">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Path" type="xs:string" />
                                <xs:element name="Delete" type="xs:boolean" />
                                <xs:element name="Filter" type="xs:string" />
                                <xs:element name="Timeout" type="xs:unsignedByte" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Queue">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Inbox" type="xs:string" />
                                <xs:element name="Outbox" type="xs:string" />
                                <xs:element name="Success" type="xs:string" />
                                <xs:element name="Fail" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="Transport">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Out" type="Transport" />
                                <xs:element name="Success" type="Transport" />
                                <xs:element name="Fail" type="Transport" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Culture" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Letters">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Letter" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string" />
                  <xs:attribute name="Frequency" type="xs:float" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="Transport">
    <xs:restriction base="xs:string">
      <xs:enumeration value="File" />
      <xs:enumeration value="Queue" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== aphawkins/old/Source/Useful/!Retired/Config/Useful.Config.xml
<?xml version="1.0" encoding="utf-8"?>

<UsefulConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Useful.Config.xsd">

    <SchemaPath>Schema</SchemaPath>
    <Consumers>
        <Consumer Name="Escom" Culture="en-GB">
          <DataService>
            <File>
              <Path>C:\Documents and Settings\Andy\My Documents\Programming\Useful\Useful.DataServices</Path>
              <Delete>true</Delete>
              <Filter>*.*</Filter>
              <Timeout>10</Timeout>
            </File>
            <Queue>
              <Inbox>.\Private$\InboxQ</Inbox>
              <Outbox>.\Private$\OutboxQ</Outbox>
              <Success>.\Private$\SuccessQ</Success>
              <Fail>.\Private$\FailQ</Fail>
            </Queue>
            <Transport>
              <Out>File</Out>
              <Success>Queue</Success>
              <Fail>File</Fail>
            </Transport>
          </DataService>
        </Consumer>
        <Consumer Name="" Culture="en-GB">
            <DataService>
                <File>
                    <Path>C:\Documents and Settings\Andy\My Documents\Programming\Useful\Useful.DataServices</Path>
                    <Delete>true</Delete>
                    <Filter>*.*</Filter>
                    <Timeout>10</Timeout>
                </File>
                <Queue>
                    <Inbox>.\Private$\InboxQ</Inbox>
                    <Outbox>.\Private$\OutboxQ</Outbox>
                    <Success>.\Private$\SuccessQ</Success>
                    <Fail>.\Private$\FailQ</Fail>
                </Queue>
                <Transport>
                    <Out>File</Out>
                    <Success>Queue</Success>
                    <Fail>File</Fail>
                </Transport>
            </DataService>
        </Consumer>
    </Consumers>
  <Letters>
    <Letter Name="A" Frequency="8.2"/>
    <Letter Name="B" Frequency="1.5"/>
    <Letter Name="C" Frequency="2.8"/>
    <Letter Name="D" Frequency="4.3"/>
    <Letter Name="E" Frequency="12.7"/>
    <Letter Name="F" Frequency="2.2"/>
    <Letter Name="G" Frequency="2.0"/>
    <Letter Name="H" Frequency="6.1"/>
    <Letter Name="I" Frequency="7.0"/>
    <Letter Name="J" Frequency="0.2"/>
    <Letter Name="K" Frequency="0.8"/>
    <Letter Name="L" Frequency="4.0"/>
    <Letter Name="M" Frequency="2.4"/>
    <Letter Name="N" Frequency="6.7"/>
    <Letter Name="O" Frequency="7.5"/>
    <Letter Name="P" Frequency="1.9"/>
    <Letter Name="Q" Frequency="0.1"/>
    <Letter Name="R" Frequency="6.0"/>
    <Letter Name="S" Frequency="6.3"/>
    <Letter Name="T" Frequency="9.1"/>
    <Letter Name="U" Frequency="2.8"/>
    <Letter Name="V" Frequency="1.0"/>
    <Letter Name="W" Frequency="2.4"/>
    <Letter Name="X" Frequency="0.2"/>
    <Letter Name="Y" Frequency="2.0"/>
    <Letter Name="Z" Frequency="0.1"/>
  </Letters>
</UsefulConfig>
